server:
    port: 8080

management:
    server.port: 8081
    endpoint:
        health:
            show-details: always
            status.order: DOWN, OUT_OF_SERVICE, OBSERVE, UNKNOWN, UP
        env.show-values: ALWAYS
        configprops.show-values: ALWAYS
    info.env.enabled: true
    endpoints.web.exposure.include: "metrics,health"

spring:
    profiles:
        active: local
    datasource:
        main:
            driver-class-name: oracle.jdbc.OracleDriver
        login:
            driver-class-name: oracle.jdbc.OracleDriver
    flyway:
        enabled: true

springdoc:
    swagger-ui:
        path: /docs/index.html
